import subprocess
import os
import config as cfg

pip_packages = {
    'numpy': 'numpy',
    'pandas': 'pandas',
    'requests': 'requests',
    'matplotlib': 'matplotlib',
    'scipy': 'scipy',
    'scikit-learn': 'scikit-learn',
    'tensorflow': 'tensorflow',
    'torch': 'torch',
    'flask': 'flask',
    'django': 'django',
    'beautifulsoup4': 'beautifulsoup4',
    'sqlalchemy': 'sqlalchemy',
    'pyqt5': 'pyqt5',
    'pygame': 'pygame',
    'pytz': 'pytz',
    'pillow': 'pillow',
    'requests': 'requests',
    'networkx': 'networkx',
    'jinja2': 'jinja2',
    'flask-restful': 'flask-restful',
    'tornado': 'tornado',
    'openai-gpt-3': 'openai-gpt-3',
    'pymongo': 'pymongo',
    'pymysql': 'pymysql',
    'pytest': 'pytest',
    'nltk': 'nltk',
    'seaborn': 'seaborn',
    'folium': 'folium',
    'pymc3': 'pymc3',
    'flask-wtf': 'flask-wtf',
    'dash': 'dash',
    'dask': 'dask',
    'cx_oracle': 'cx_oracle',
    'bcrypt': 'bcrypt',
    'celery': 'celery',
    'pyarrow': 'pyarrow',
    'pyspark': 'pyspark',
    'plotly': 'plotly',
    'kafka-python': 'kafka-python',
    'fastapi': 'fastapi',
    'pytest-django': 'pytest-django',
    'pyodbc': 'pyodbc',
    "mypdf2": "PyPDF2",
    "click": "click"
}


apt_packages = {"git": "git",
    "ansible":"ansible",
    "nano": "nano",
    "vim": "vim",
    "htop": "htop",
    "curl": "curl",
    "wget": "wget",
    "python3": "python3",
    "python3-pip": "python3-pip",
    "apache2": "apache2",
    "nginx": "nginx",
    "mysql-server": "mysql-server",
    "postgresql": "postgresql",
    "php": "php",
    "nodejs": "nodejs",
    "npm": "npm",
    "openjdk-11-jdk": "openjdk-11-jdk",
    "gcc": "gcc",
    "g++": "g++",
    "make": "make",
    "virtualbox": "virtualbox",
    "docker": "docker",
    "docker-compose": "docker-compose",
    "ansible": "ansible",
    "wireshark": "wireshark",
    "openssh-server": "openssh-server",
    "tmux": "tmux",
    "screen": "screen",
    "emacs": "emacs",
    "gparted": "gparted",
    "ffmpeg": "ffmpeg",
    "vlc": "vlc",
    "libreoffice": "libreoffice",
    "gimp": "gimp",
    "inkscape": "inkscape",
    "blender": "blender",
    "audacity": "audacity",
    "rhythmbox": "rhythmbox",
    "transmission": "transmission",
    "clamav": "clamav",
    "fail2ban": "fail2ban",
    "ufw": "ufw",
    "nmap": "nmap",
    "lynx": "lynx",
    "elinks": "elinks",
    "irssi": "irssi",
    "mutt": "mutt",
    "transmission-cli": "transmission-cli",
    "samba": "samba",
    "nfs-common": "nfs-common",
    "cifs-utils": "cifs-utils",
    "sshfs": "sshfs",
    "zip": "zip",
    "unzip": "unzip",
    "rar": "rar",
    "unrar": "unrar",
    "gnome-terminal": "gnome-terminal",
    "xfce4-terminal": "xfce4-terminal",
    "konsole": "konsole",
    "terminator": "terminator",
    "ranger": "ranger",
    "midnight-commander": "midnight-commander",
    "synaptic": "synaptic",
    "filezilla": "filezilla",
    "putty": "putty",
    "xrdp": "xrdp",
    "remmina": "remmina",
    "pidgin": "pidgin",
    "hexchat": "hexchat",
    "teamviewer": "teamviewer",
    "wine": "wine",
    "clamtk": "clamtk",
    "xclip": "xclip",
    "meld": "meld",
    "bleachbit": "bleachbit",
    "gufw": "gufw",
    "gdebi": "gdebi",
    "keepassxc": "keepassxc",
    "transmission-gtk": "transmission-gtk",
    "qbittorrent": "qbittorrent",
    "deluge": "deluge",
    "hexedit": "hexedit",
    "radare2": "radare2",
    "netcat": "netcat",
    "john": "john",
    "hydra": "hydra",
    "nikto": "nikto",
    "aircrack-ng": "aircrack-ng",
    "ettercap-graphical": "ettercap-graphical",
    "tcpdump": "tcpdump",
    "openssh-client": "openssh-client",
    "rsync": "rsync",
    "ffmpeg": "ffmpeg",
    "audacity": "audacity",
    "darktable": "darktable",
    "krita": "krita",
    "sed": "sed",}

dummy_version = ['1.1.1', '1.1.2', '1.1.3', '2.0']
    
    
def get_package_versions(mode, package_name):
    if mode == "apt":
        version = ["latest"]
    else:
        output = subprocess.check_output(f"pip index versions {package_name} | tail -1 | cut -d ':' -f 2", shell=True)
        version = output.decode().strip().split(", ")
    return version


build_in_packages = [
    "chmod",
    "chown",
    "chroot",
    "cp",
    "dd",
    "df",
    "du",
    "lm",
    "ls",
    "mkdir",
    "mv",
    "rm",
    "rmdir",
    "rmdir",
    "touch",
    "basename",
    "cat",
    "comm",
    "cut",
    "dirname",
    "echo",
    "expand",
    "false",
    "fmt",
    "fold",
    "head",
    "join",
    "paste",
    "seq",
    "sleep",
    'sort',
    "split",
    "tail",
    "tee",
    "test",
    "tr",
    "true",
    "uniq",
    "wc",
    "yes",
    "date",
    "env",
    "groups",
    "hostname",
    "id",
    "nice",
    "pwd",
    "su",
    "uname",
    "who",
    "whoami"
]

python_versions = [
    "3.13-dev",
    "3.13.0a1",
    "3.12-dev",
    "3.12.0",
    "3.11.6",
    "3.11.5",
    "3.11.4",
    "3.11.3",
    "3.11.2",
    "3.11.1",
    "3.11-dev",
    "3.11.0",
    "3.10.13",
    "3.10.12",
    "3.10.11",
    "3.10.10",
    "3.10.9",
    "3.10.8",
    "3.10.7",
    "3.10.6",
    "3.10.5",
    "3.10.4",
    "3.10.3",
    "3.10.2",
    "3.10.1",
    "3.10-dev",
    "3.9.18",
    "3.9.17",
    "3.9.16",
    "3.9.15",
    "3.9.14",
    "3.9.13",
    "3.9.12",
    "3.9.11",
    "3.9.10",
    "3.9.9",
    "3.9.8",
    "3.9.7",
    "3.9.6",
    "3.9.5",
    "3.9.4",
    "3.9.2",
    "3.9.1",
    "3.9.0",
    "3.8.18",
    "3.8.17",
    "3.8.16",
    "3.8.15",
    "3.8.14",
    "3.8.13",
    "3.8.12",
    "3.8.11",
    "3.8.10",
    "3.8.9",
    "3.8.8",
    "3.8.7",
    "3.8.6",
    "3.8.5",
    "3.8.4",
    "3.8.3",
    "3.8.2",
    "3.8.1",
    "3.8-dev",
    "3.8.0",
    "3.7.18",
    "3.7.17",
    "3.7.16",
    "3.7.15",
    "3.7.14",
    "3.7.13",
    "3.7.12",
    "3.7.11",
    "3.7.10",
    "3.7.9",
    "3.7.8",
    "3.7.7",
    "3.7.6",
    "3.7.5",
    "3.7.4",
    "3.7.3",
    "3.7.2",
    "3.7.1",
    "3.7-dev",
    "3.7.0",
    "3.6.15",
    "3.6.14",
    "3.6.13",
    "3.6.12",
    "3.6.11",
    "3.6.10",
    "3.6.9",
    "3.6.8",
    "3.6.7",
    "3.6.6",
    "3.6.5",
    "3.6.4",
    "3.6.3",
    "3.6.2",
    "3.6.1",
    "3.6-dev",
    "3.6.0",
    "3.5.10",
    "3.5.9",
    "3.5.8",
    "3.5.7",
    "3.5.6",
    "3.5.5",
    "3.5.4",
    "3.5.3",
    "3.5.2",
    "3.5.1",
    "3.5-dev",
    "3.5.0",
    "3.4.10",
    "3.4.9",
    "3.4.8",
    "3.4.7",
    "3.4.6",
    "3.4.5",
    "3.4.4",
    "3.4.3",
    "3.4.2",
    "3.4.1",
    "3.4-dev",
    "3.4.0",
    "3.3.7",
    "3.3.6",
    "3.3.5",
    "3.3.4",
    "3.3.3",
    "3.3.2",
    "3.3.1",
    "3.3.0",
    "3.2.6",
    "3.2.5",
    "3.2.4",
    "3.2.3",
    "3.2.2",
    "3.2.1",
    "3.2.0",
    "3.1.5",
    "3.1.4",
    "3.1.3",
    "3.1.2",
    "3.1.1",
    "3.1.0",
    "3.0.1",
    "2.7.18",
    "2.7.17",
    "2.7.16",
    "2.7.15",
    "2.7.14",
    "2.7.13",
    "2.7.12",
    "2.7.11",
    "2.7.10",
    "2.7.9",
    "2.7.8",
    "2.7.7",
    "2.7.6",
    "2.7.5",
    "2.7.4",
    "2.7.3",
    "2.7.2",
    "2.7.1",
    "2.7-dev",
    "2.6.9",
    "2.6.8",
    "2.6.7",
    "2.6.6",
    "2.6.5",
    "2.6.4",
    "2.6.3",
    "2.6.2",
    "2.6.1",
    "2.6.0",
    "2.5.6",
    "2.5.5",
    "2.5.4",
    "2.5.3",
    "2.5.2",
    "2.5.1",
    "2.5.0",
    "2.4.6",
    "2.4.5",
    "2.4.4",
    "2.4.3",
    "2.4.2",
    "2.4.1",
    "2.4.0",
    "2.3.7",
    "2.2.3",
    "2.1.3",
]

os_versions = ['debian:10', 'debian:11', 'debian:12','ubuntu:20.04', 'ubuntu:22.04', 'ubuntu:23.04']


def load_apt_to_dict(os_name):
    file_content = []
    parent_directory = cfg.path_to_project
    try:
        with open(f'{parent_directory}/modules_listings/apt/{os_name}.txt', 'r') as file:
            content = file.read()
            lines = content.split('\n')
            file_content = {line.strip(): line.strip() for line in lines if line.strip()}
    except FileNotFoundError:
        file_content = None

    return file_content


def load_pip_to_dict():
    file_content = []
    parent_directory = cfg.path_to_project
    try:
        with open(os.path.join(parent_directory, "modules_listings", "pip", "all_pip_packages.txt"), 'r') as file:
            content = file.read()
            lines = content.split('\n')
            file_content = {line.strip(): line.strip() for line in lines if line.strip()}
    except FileNotFoundError:
        file_content = None

    return file_content
